In [1]:
import os
import warnings
import geopandas as gpd

import extracting_points_from_polygons as pp

The following warning comes up with pp.sample_naip_from_polys, we'll catch it to ease the reading of notebook

`/srv/conda/envs/notebook/lib/python3.8/site-packages/pandas/core/dtypes/cast.py:122: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)`

In [2]:
def naip_sample_no_warnings(polys,itemid,proportion=0.2):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        df = pp.sample_naip_from_polys(polys,itemid,proportion)
    return df

In [3]:
itemid = 'ca_m_3411934_sw_11_060_20180722_20190209'

root = os.path.join(os.getcwd(),'aux_data','polygons_from_naip_images')

### Extract points from campuspoint2018polys3.shp

In [4]:
file = 'campuspoint2018polys3/campuspoint2018polys3.shp'
polys = gpd.read_file(os.path.join(root,file))

naip_sample_no_warnings(polys,itemid)

,geometry,x,y,iceplant,r,g,b,nir,year,month,day
0,POINT (238343.42981319653 3810848.805207873),238343.429813,3.810849e+06,1,93,88,93,141,2018,7,22
1,POINT (238343.54673072175 3810846.093093588),238343.546731,3.810846e+06,1,85,85,89,137,2018,7,22
2,POINT (238344.86438268574 3810845.534717399),238344.864383,3.810846e+06,1,89,85,91,133,2018,7,22
3,POINT (238342.5430043139 3810847.57428281),238342.543004,3.810848e+06,1,92,87,95,134,2018,7,22
4,POINT (238345.24006490404 3810849.145357247),238345.240065,3.810849e+06,1,86,81,88,137,2018,7,22
...,...,...,...,...,...,...,...,...,...,...,...
326,POINT (239557.42343425404 3812086.1513641356),239557.423434,3.812086e+06,0,54,69,71,100,2018,7,22
327,POINT (239568.07540584923 3812106.3295439086),239568.075406,3.812106e+06,0,78,100,82,168,2018,7,22
328,POINT (239571.13427138602 3812100.2575197807),239571.134271,3.812100e+06,0,78,78,86,88,2018,7,22
329,POINT (239550.85198595884 3812087.3235837673),239550.851986,3.812087e+06,0,68,75,79,98,2018,7,22
330,POINT (239557.11801803412 3812098.148459577),239557.118018,3.812098e+06,0,63,81,72,155,2018,7,22

### Extract points from trees.shp

In [5]:
file ='trees/trees.shp' 
polys = gpd.read_file(os.path.join(root,file))

polys['iceplant']=0
naip_sample_no_warnings(polys,itemid,0.1)

,geometry,x,y,iceplant,r,g,b,nir,year,month,day
0,POINT (238100.0461949407 3811295.4545030612),238100.046195,3.811295e+06,0,110,102,98,166,2018,7,22
1,POINT (238099.87094423154 3811288.1446151566),238099.870944,3.811288e+06,0,134,121,113,163,2018,7,22
2,POINT (238113.53434855543 3811286.7630826873),238113.534349,3.811287e+06,0,64,68,76,147,2018,7,22
3,POINT (238108.03470101196 3811300.2439471227),238108.034701,3.811300e+06,0,67,65,78,135,2018,7,22
4,POINT (238099.06344234096 3811298.787311951),238099.063442,3.811299e+06,0,136,120,116,158,2018,7,22
...,...,...,...,...,...,...,...,...,...,...,...
159,POINT (238150.70569671772 3811260.693698522),238150.705697,3.811261e+06,0,64,70,77,144,2018,7,22
160,POINT (238152.85297321767 3811246.717337698),238152.852973,3.811247e+06,0,41,52,68,59,2018,7,22
161,POINT (238153.95120151463 3811255.156746631),238153.951202,3.811255e+06,0,31,41,63,27,2018,7,22
162,POINT (238145.7127407422 3811256.077108729),238145.712741,3.811256e+06,0,68,64,80,134,2018,7,22
163,POINT (238159.12304886756 3811256.5689395317),238159.123049,3.811257e+06,0,35,42,64,21,2018,7,22

In [6]:
geo_train_set = gpd.GeoDataFrame(train_set, crs=polys.crs)
geo_train_set

NameError: name 'train_set' is not defined