In [9]:
import os
import warnings
import geopandas as gpd

import extracting_points_from_polygons as pp

In [11]:
itemid = 'ca_m_3411934_sw_11_060_20180722_20190209'
fp = os.path.join(os.getcwd(),'aux_data','polygons_from_naip_images',
                          'campuspoint2018polys3/campuspoint2018polys3.shp')
polys = gpd.read_file(fp)

/srv/conda/envs/notebook/lib/python3.8/site-packages/pandas/core/dtypes/cast.py:122: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)

In [11]:
with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    test = pp.sample_naip_from_polys(polys,itemid)
test

,geometry,x,y,iceplant,r,g,b,nir,year,month,day
0,POINT (238342.0015851332 3810852.328035099),238342.001585,3.810852e+06,1,88,80,87,141,2018,7,22
1,POINT (238346.0333284369 3810850.9221978993),238346.033328,3.810851e+06,1,87,82,90,134,2018,7,22
2,POINT (238346.31045910466 3810848.8287792746),238346.310459,3.810849e+06,1,93,85,93,135,2018,7,22
3,POINT (238345.02332966542 3810850.1214733203),238345.023330,3.810850e+06,1,94,88,94,136,2018,7,22
4,POINT (238346.8738203884 3810850.367709071),238346.873820,3.810850e+06,1,86,81,86,134,2018,7,22
...,...,...,...,...,...,...,...,...,...,...,...
326,POINT (239555.70319355754 3812101.935223281),239555.703194,3.812102e+06,0,27,42,58,85,2018,7,22
327,POINT (239555.56462386323 3812092.040854915),239555.564624,3.812092e+06,0,74,101,76,169,2018,7,22
328,POINT (239546.92598946163 3812086.773930219),239546.925989,3.812087e+06,0,51,68,66,125,2018,7,22
329,POINT (239550.98929619277 3812092.0183810596),239550.989296,3.812092e+06,0,85,110,77,180,2018,7,22
330,POINT (239567.09190543857 3812090.432691392),239567.091905,3.812090e+06,0,59,80,71,173,2018,7,22

In [4]:
geo_train_set = gpd.GeoDataFrame(train_set, crs=polys.crs)
geo_train_set

NameError: name 'train_set' is not defined